Insert into STAF_TRANSACTIONCODEBANK 
  (INTID_TRANSACTIONCODE,INTID_BANK,STRORBIDSTRRT_RETAILSTORE,DATCREATE_TCB,
   DATMODIFIED_TCB,BITISENABLE_TCB,STRORBIDLOGIN_USER) 
values 
  ('510', '55', '01041', sysdate, null, '1', 'bopos');
  
Insert into STAF_TRANSACTIONCODEBANK 
  (INTID_TRANSACTIONCODE,INTID_BANK,STRORBIDSTRRT_RETAILSTORE,DATCREATE_TCB,
   DATMODIFIED_TCB,BITISENABLE_TCB,STRORBIDLOGIN_USER) 
values 
  ('520', '55', '01041', sysdate, null, '1', 'bopos');  
  
  
  


INTID_TRANSACTIONCODE  
510         T. DEBITO
520         T. CREDITO

INTID_BANK  
84           ACTIVO
83           BANCO NACIONAL DE CREDITO
11           BANESCO
85           BANPLUS
86           BICENTENARIO
34           B.O.D.
55           CARONI
9               DEL CARIBE
13           EXTERIOR
42           FONDO COMUN
3               MERCANTIL
1             PROVINCIAL
4               VENEZUELA
12           VZLANO DE CREDITO