SELECT A.ID_STR_RT COD_TIENDA,
	    PA.NM_LOC NOMBRE,
	    A.ID_WS CAJA,
	    A.AI_TRN TRANSACCION,
	    A.DC_DY_BSN FECHA,
	    RT.MO_TND_TOT MONTO_TOTAL,
	    LT.TY_TND TIPO_PAGO,
	    LT.MO_ITM_LN_TND MONTO_PAGO,
		    CASE WHEN A.TX_MOD = 0
		THEN
			'DEFAULT'
		ELSE
			'CAMBIO'
		END
	MODO_TAX,
	    A.PE_TX PORCENTAJE,
	    A.ID_UNQ CODIGO_TAX,
		    CASE WHEN B.SC_TRN = 2
		THEN
			'EXITOSO'
		ELSE
			'CANCELADA'
		END
	STATUS,
	    B.ID_OPR CAJERO,
	    E.ID_LOGIN,
	    E.NM_EM NOMBRE_CAJ
FROM COUSER.TR_LTM_SLS_RTN_TX A
	INNER JOIN COUSER.TR_TRN B ON ( A.ID_STR_RT = B.ID_STR_RT
		AND			A.ID_WS = B.ID_WS
		AND			A.DC_DY_BSN = B.DC_DY_BSN
		AND			A.AI_TRN = B.AI_TRN
	)
	INNER JOIN COUSER.PA_STR_RTL PA ON ( B.ID_STR_RT = PA.ID_STR_RT
	)
	INNER JOIN EMPLOYEES E ON ( B.ID_STR_RT = E.ID_STR_RT
		AND			B.ID_OPR = E.ID_EM
	)
LEFT JOIN COUSER.TR_LTM_TND LT
ON ( LT.ID_STR_RT = B.ID_STR_RT
	AND		LT.ID_WS = B.ID_WS
	AND		LT.DC_DY_BSN = B.DC_DY_BSN
	AND		LT.AI_TRN = B.AI_TRN
)
	INNER JOIN COUSER.TR_RTL RT ON ( RT.ID_STR_RT = B.ID_STR_RT
		AND			RT.ID_WS = B.ID_WS
		AND			RT.DC_DY_BSN = B.DC_DY_BSN
		AND			RT.AI_TRN = B.AI_TRN
	)
WHERE A.DC_DY_BSN >= '2016-12-27'
AND	A.PE_TX IN (		10	)
AND	A.AI_LN_ITM = 0
--AND A.TX_MOD IN(0,3)
--AND LT.TY_TND IN('CASH')
AND	LT.TY_TND NOT IN (
		'DBIT', 'CRDT', 'FCRD'	)
AND ( RT.MO_TND_TOT <> LT.MO_ITM_LN_TND
	OR		RT.MO_TND_TOT = LT.MO_ITM_LN_TND
) ORDER BY
	B.ID_STR_RT,
	B.DC_DY_BSN,
	4 ASC;